### PR TITLE
Add weee tax to product price

### PR DESCRIPTION
**Pull request by trosyno**
Adds weee tax (European tax on electronic products) to the price
see #813

### CODE REVIEW

**Comment by trosyno** [comment]
#829

**Comment by JanPetr** [comment]
Thanks for the PR @trosyno!
Is the WEEE module always present in Magento instance? Is that something we can rely on? I'd put there a check if the WEEE is present and enabled.
Could you add it?

**Comment by trosyno** [comment]
You're right! I've just added the check.

**Comment by JanPetr** [comment]
Thanks @trosyno, everything seems to be working now! Thanks for your contribution 💯

**Pull request merged**
