### PR TITLE
Now when you re-index suggestions it deletes it's settings. This comm…

### PR DESCRIPTION
**Pull request by JanPetr**
…it fixes that.

### CODE REVIEW

**Comment by maxiloc** [comment]
👍

**Comment by JanPetr** [comment]
Not really :)) I found a better solution.

**Comment by maxiloc** [comment]
It's ok to set settings at each reindex

**Comment by JanPetr** [comment]
Yes, but it's not OK to set settings to full index. It's always better to set it to empty `tmp` index :)

**Comment by JanPetr** [comment]
Now you can review :)

**Comment by maxiloc** [comment]
ah yes 😄

**Pull request merged**
