### PR TITLE
Fix wiped out settings on reindex with enabled indexing queue

### PR DESCRIPTION
**Pull request by JanPetr**

### CODE REVIEW

**Comment by maxiloc** [comment]
👍

**Comment by royduin** [comment]
Good one! I'm experiencing the same issue at some customers running on 1.8.0, looking forward to the merge and new release.

**Comment by JanPetr** [comment]
I'd say more "nasty one" than a "good one" :( Feel free to grab the patch from here and apply it for your customer. I'll be happy to hear your feedback and if it fixed your customer's issue before merging :)

**Comment by royduin** [comment]
Haha, you're right. It's a nasty one 😜 I'm going to roll it out and the feedback is coming 👍

**Comment by JanPetr** [comment]
Thanks, looking forward!

**Comment by royduin** [comment]
So far so good with two customers 😎

**Comment by JanPetr** [comment]
So good to hear! Thanks @royduin, I will merge and hopefully release by the end of the week. Thanks for your help 👍

**Pull request merged**
