### PR TITLE
Change algolia queue data column type to TEXT

### PR DESCRIPTION
**Pull request by VincentMarmiesse**
Hello,

The `data` column of the queue table (`algoliasearch_queue`) is a `VARCHAR(5000)` so if you reindex more than 1000 products for example, it will cut the json and make it invalid.

This PR updates the type to `TEXT`.

### CODE REVIEW

**Comment by VincentMarmiesse** [comment]
I don't know what's the issue with the StyleCI analysis, you can edit my PR if you want.

**Comment by JanPetr** [comment]
Hello @VincentMarmiesse,
thank you for PR, definitelly makes sense! 🎉 

Can you please just revert `config.xml`, it'll be updated on release of the 1.7.1 version.
An can you fix styles? https://styleci.io/analyses/X0pmAW

Does this PR solves your issue with deleted products?

**Comment by VincentMarmiesse** [comment]
Hello @JanPetr,

Ok for `config.xml`.
What is the styles issue? I don't see any difference between my line and his.

My issue with deleted products has been fixed by increasing the `Max number of element per indexing job` to 10000.

**Comment by JanPetr** [comment]
> What is the styles issue? I don't see any difference between my line and his.

Add a new line after `$installer->endSetup();`

**Comment by VincentMarmiesse** [comment]
PR updated ;)

**Comment by JanPetr** [comment]
Thanks. I just realized the PR is targeting wrong branch. Can you make a new PR targeting `develop` instead of `master`? And can you squash those 2 commits?

Thank you!

**Pull request closed without merging**
