### PR TITLE
Removed the No or N/A values from being indexed

### PR DESCRIPTION
**Pull request by royduin**
If a product attribute is empty, Magento is returning N/A or No. By excluding these values we get cleaner facets instead of a lot of values in a facet with just one option: N/A.

### CODE REVIEW

**Comment by JanPetr** [comment]
Hello @royduin,
thanks for contribution. Unfortunatelly this is not something we can add to the extension like that as it breaks backward compatibility and now all attributes with value "No" will be removed from index. And that will cause troubles with people who want to index their "No" attributes.
Can you make it configurable with default value set on off?

**Comment by royduin** [comment]
Something like this @JanPetr?

**Comment by JanPetr** [comment]
Exactly @royduin, thanks!
Just two things - can you make the header shorter and explain what the settings mean below in comments of the field. Something like that:
screenshot 2016-08-19 10 42 45

And can you develop it on top of `develop` branch instead of the `master` one? And target the PR on `develop` as well?

Thanks!

**Comment by royduin** [comment]
Done, see: https://github.com/algolia/algoliasearch-magento/pull/554

**Pull request closed without merging**
