### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by JosephMaxwell**
I brought it in using the same idea that was already in place in the JS file. As I have time, I would like to optimize the JS file, as there is a lot that can be done there, and as such, I followed the style of the script and not best practice when writing the update :). Let me know if you see any optimizations that are good.

### CODE REVIEW

**Comment by maxiloc** [comment]
@JosephMaxwell it's really good.

However we are working on integrating https://github.com/algolia/instantsearch.js and https://github.com/algolia/autocomplete.js in the extension that will change the code regarding UI/UX. So we will not merge that right now.

If you want to have a look at what has already been done you can check the instantsearch.js branch => https://github.com/algolia/algoliasearch-magento/blob/instantsearch.js/design/frontend/template/topsearch.phtml

**Comment by JosephMaxwell** [comment]
@maxiloc, sounds good. Thank you. The updates on the `instantsearch.js` branch look great! Will this version have a "view all"? If not, I'll see about adding that in. Do you have a rough ETA for when this branch will be merged?

**Comment by maxiloc** [comment]
@JosephMaxwell Currently it's not part of the library but can definitely be a widget that we can add to the extension. This should be ready within the next month

**Comment by maxiloc** [comment]
This is already doable (develop branch for now) with the hitsPerPageSelector widget of instantsearch.
You can check https://community.algolia.com/instantsearch.js/documentation/#hitsperpageselector for more details.

I am closing this one

**Pull request closed without merging**
