### PR TITLE
Making product types mappable via configuration

### PR DESCRIPTION
**Pull request by JosephMaxwell**
Thanks for the comments. I have moved my work to the develop branch and the lookup to the config helper.

### CODE REVIEW

**Comment by JosephMaxwell** [comment]
Do you have a rough idea as to when you can merge these changes? We are looking to push some code that uses these updates.

**Comment by maxiloc** [comment]
Now :smile:. It will be part of the next release, probably early next week

**Comment by maxiloc** [comment]
Thank for contributing

**Comment by JosephMaxwell** [comment]
Awesome, thank you.

**Pull request merged**
