### PR TITLE
Attempt to fix per-store product and category URLs

### PR DESCRIPTION
**Pull request by Zifius**

### CODE REVIEW

**Comment by Zifius** [comment]
@maxiloc any feedback on this?

**Comment by maxiloc** [comment]
@Zifius This is on my to do list. I'll try to check that this week

**Comment by maxiloc** [comment]
It's indeed a better way to get the url I am merging this

**Comment by maxiloc** [comment]
@Zifius Thanks for contributing

**Comment by Zifius** [comment]
You are welcome @maxiloc. Hope this doesn't break things. I'm not too familiar with the store emulation mode

**Pull request merged**
