### PR TITLE
Close the DB connection when the queue runner is done

### PR DESCRIPTION
**Pull request by JanPetr**

### CODE REVIEW

**Comment by maxiloc** [comment]
Isn't supposed to be done by Magento

**Comment by JanPetr** [comment]
Should be, but we had issue from a customer about alive connections from QueueRunner.
So I wouldn't rely on it anymore and close it manually here.

**Comment by maxiloc** [comment]
makes sense but I am a bit worried about magento needing the connection somehow and failing (not in our code) because there is no connection anymore

**Comment by JanPetr** [comment]
I tested it and didn't find any issue with that. When merged, it's going to live in `develop` branch for a while and we will see if it's causing issues on different instances.

**Comment by maxiloc** [comment]
👍

**Pull request merged**
