### PR TITLE
Set configurable product out of stock, if all the children is out of stock

### PR DESCRIPTION
**Pull request by kurtinge**
Sets the configurable product as out-of-stock when all the children is out of stock.

### CODE REVIEW

**Comment by redox** [comment]
Ah good catch @kurtinge; I'll let @maxiloc handle the merge but it looks good :+1:

**Comment by maxiloc** [comment]
@kurtinge I am not sure why we need this, Magento is supposed to put it out of stock by himself, no ?

Also the modification you made does not do exactly what it supposed to. Right now, it put the main product out of stock if one of the additional attribute is not set in all the children even if they are in stock.

**Comment by maxiloc** [comment]
@kurtinge I am closing this, feel free to re-open if needed

**Comment by kurtinge** [comment]
The Configurable product in Magento (or even grouped products) does not update the stockitem  automaticly when all the children is out of stock.

The check on line 588 will always be true as long as the status on the configurable product is set to "in stock":
$customData['in_stock'] = (int) $stockItem->getIsInStock();

Since Algolia is using this to see if the product is sellable or not, the configurable product should be set out of stock if all the sub products is out of stock.

**Comment by kurtinge** [comment]
I've made a new pull request for this, fixing the issue with the value check.

**Pull request closed without merging**
