### PR TITLE
Do not process duplicate products

### PR DESCRIPTION
**Pull request by JanPetr**

### CODE REVIEW

**Comment by maxiloc** [comment]
Why does this happens ?

**Comment by JanPetr** [comment]
https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Model/Indexer/Abstract.php#L55-L63
2 different configurable products can be composed by same simple products

**Comment by maxiloc** [comment]
Maybe if would be better to put the unique there no ?

**Comment by JanPetr** [comment]
I put it lower as the method can be called from other places then just Abstract indexer and there is the last spot before batching.

**Comment by maxiloc** [comment]
Ok works for me

**Pull request merged**
