### PR TITLE
Handle MSRP price

### PR DESCRIPTION
**Pull request by Zifius**
Need to check for the case when both special price and MSRP are set, don't merge yet I'll test and update if needed

### CODE REVIEW

**Comment by maxiloc** [comment]
@Zifius For me MSRP price should not be a special price, it should replace the default price, no ? Do we agree than if map if enabled it should not display the default price but the manufacturer price ?

**Comment by Zifius** [comment]
1. Well I think MSRP > normal price > special price. Also according to https://mage-user-guide.atlassian.net/wiki/display/MUG/9.6+Minimum+Advertised+Price if special price set it should "considered to be the actual price for MAP" which I don't really get
2. Agreed, according to the page above "will not be indexed by search engines", thought in the project I work on MAP setting is not enabled and MSRP used as "old" (and bigger) price

**Comment by maxiloc** [comment]
@Zifius With this commit https://github.com/algolia/algoliasearch-magento/commit/d82d8634758bf0ecf0776cb155fd78073d50ec3f the behavior is that if you have map enabled it will just not index price.
Are enabling map and want price to show up ?

**Comment by Zifius** [comment]
No, not enabling the MAP. Just want MSRP to be indexed as "old" price to "default_original_formated" field

**Comment by maxiloc** [comment]
Yes so I guess this is not something we want in the extension because Magento is not handling that this way. But yes what you do is definitely good for what you are trying to do so you keep the fix on your instance

**Comment by Zifius** [comment]
Agreed!

**Pull request closed without merging**
