### PR TITLE
use algoliasearch-extensions-bundle

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by vvo** [comment]
cc @redox @maxiloc

**Comment by maxiloc** [comment]
Merged on develop

**Comment by vvo** [comment]
@maxiloc You can do merges on the command line so my commits are not lost :) Ill submit to develop next time

**Comment by vvo** [comment]
ohoh this is what you did :+1: too much commits!

**Comment by maxiloc** [comment]
yes :)

**Pull request closed without merging**
