### PR TITLE
Code improvements - PSR2, annotations

### PR DESCRIPTION
**Pull request by JanPetr**
@maxiloc I made code_style improvements to follow mostly PSR 2 standarts. I added annotations to most of the class variables so autocomplete can work ;) Please, take a look into that and tell me what you don't like about the code style. We can discuss it and agree on the best solution. Thx ;)

### CODE REVIEW

**Comment by maxiloc** [comment]
Let's setup  StyleCI after this one is merged

**Comment by JanPetr** [comment]
> Let's setup StyleCI after this one is merged

For sure. I can include it even into this PR, hm?

**Comment by maxiloc** [comment]
yes we can do it now

**Comment by JanPetr** [comment]
ok, will do ;) Let me know if you have some issues with the CS I used

**Comment by maxiloc** [comment]
For the CS all for me, let's just make sure we have the same rules than algoliasearch-client-php

**Comment by JanPetr** [comment]
Okey, StyleCI configured and `.php_cs` is configured the same way as in algoliaseach-client-php ;)

**Pull request merged**
