### PR TITLE
Enable Rewrite for Algolia_Algoliasearch_Model_Resource_Engine

### PR DESCRIPTION
**Pull request by michaelscheel**
The engine shouldn't be loaded via direct initialization and should instead follow Magento best practice to allow rewrites by third party developers.

### CODE REVIEW

**Comment by michaelscheel** [comment]
I guess it makes no sense to add things to the queue multiple times (e.g. when a product is saved multiple times within a few minutes and the queue is already full).

**Comment by julienbourdeau** [comment]
Hi @michaelscheel,

Thanks for your contribution!

Would you mind cleaning your branch so you only have the first commit? The following commands should of the trick.

```
git reset --hard fac05593aba5c9ca870a6459d441ca22afe6bbc5
git push -f
```

**Comment by michaelscheel** [comment]
Hi @julienbourdeau,

ok - it's done.

**Comment by julienbourdeau** [comment]
I have run the tests locally and they pass 👍 

Thanks for your contribution!

**Pull request merged**
