### PR TITLE
Hide IS page info panel on no results

### LINKED ISSUE #538: When no results are displayed on IS page "SORT BY" is still visible and should not be
screenshot 2016-08-09 18 02 37

### PR DESCRIPTION
**Pull request by JanPetr**
Fixes #538

### CODE REVIEW

**Comment by maxiloc** [comment]
What's the issue showing it when there is no result ?

**Comment by JanPetr** [comment]
It does not look nice, it's empty on it's left side and on the right side there is a "sort" select box but you have nothing to sort ...

**Comment by maxiloc** [comment]
Indeed makes sense, I usually prefer to hide/show with a class, but that's a personal thing 😄 .
LGTM

**Comment by JanPetr** [comment]
Class is definitelly better and easier to override. Will change, thanks for the tip @maxiloc

**Pull request merged**
