### PR TITLE
Added feature to enable/disable alogoliasearch module

### PR DESCRIPTION
**Pull request by manish172**

### CODE REVIEW

**Comment by maxiloc** [comment]
@manish172 Thanks that is a good start to fix #185

I can not merge that as it is right now. The main reason is that we want to be able to index to Algolia launching full reindex even if store is disable. Not sure yet of the best way to implement that. Maybe we need two configs for disableling completly.

**Comment by maxiloc** [comment]
@manish172 I just implemented it with 3a87884. Your work was the foundation but I needed to add a lot of logic to handle #185.

**Comment by manish172** [comment]
Great! Thanks for adding this. It's a big addition for the customers who has big catalog and many stores which they are using only in backend for ebay/amazon etc. 

There is one more thing related to indexing performance. You had included ordered_qty and rating_summary in function rebuildStoreProductIndexPage (line 371 and 372) but if there there thousands of order then it makes indexing very slow. 

If we have some admin settings to include/exclude ordered_qty and rating_summary then it would be easy to exclude these data from indexing for stores which have thousand of products.

Please let me know your feedback on above mentioned indexing performance issue.

**Comment by maxiloc** [comment]
@manish172 The thing is having ordered_qty remove from the customRanking will hurt relevance really bad. We are aware of the performance issue, but for now I think it's better to have a long indexing and good relevance than the opposite.
I am open to suggestions on how to optimise those queries but removing them from indexing is not a good solution.

**Comment by manish172** [comment]
@maxiloc Could you please let me know that when are you  going to merge your recent changes into master branch?

**Comment by maxiloc** [comment]
@manish172 Do not know yet. I still need to do some testing

**Comment by manish172** [comment]
@maxiloc ok. no problem. please let me once you will merge your changes.

**Pull request closed without merging**
