### PR TITLE
Prevent backend rendering

### PR DESCRIPTION
**Pull request by JanPetr**
This feature prevents category pages to be rendered on backed when they use Algolia. As a result the rendering should be much faster. Implements #877 

**TODO:**

- [x] User-agent detection to run backend rendering for specified UAs
- [x] Description of the configuration input
- [x] Documentation page (https://github.com/algolia/magento/pull/73)
- [x] Test accessibility of website

### CODE REVIEW

**Comment by alexgran** [comment]
Hi, works fine for me, even in heavily customised Apptha MArketplace based website.
I think we should use the same approach for product search?

**Comment by JanPetr** [comment]
Thanks @alexgran!
I removed few more templates from backend rendering including search page.

Can you confirm that everything still works on your side and that you can see a performance improvement?

Thank you!

**Comment by JanPetr** [comment]
Hello @alexgran,
did you have some time to try the latest changes in this PR?

**Comment by alexgran** [comment]
Hi @JanPetr , currently on holiday, but got a developer on the task. Will have feedback next week.

**Comment by alexgran** [comment]
@JanPetr Works like a charm. On a non optimised development server, this gives around 50% improvment on the page with all products.

**Comment by JanPetr** [comment]
Thanks for your feedback @alexgran 💯

**Pull request merged**
